CREATE TABLE TAREFA(
	IDTAREFA	UNIQUEIDENTIFIER	NOT NULL,
	NOME		NVARCHAR(150)		NOT NULL,
	DATA		DATE				NOT NULL,
	HORA		TIME				NOT NULL,
	DESCRICAO	NVARCHAR(150)		NOT NULL,
	PRIORIDADE	NVARCHAR(15)		NOT NULL,
	IDUSUARIO	UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(IDTAREFA),
	FOREIGN KEY(IDUSUARIO)
		REFERENCES USUARIO(IDUSUARIO))
GO